//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LooksFamiliar.Microservices.Ref.Admin.SDK {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Errors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LooksFamiliar.Microservices.Ref.Admin.SDK.Errors", typeof(Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RefM Error - Entity Attribute with key {0} and value {1} not created.
        /// </summary>
        internal static string ERR_REFM_ATTR_NOT_CREATED {
            get {
                return ResourceManager.GetString("ERR_REFM_ATTR_NOT_CREATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RefM Error - Entity Attribute with id {0} not deleted.
        /// </summary>
        internal static string ERR_REFM_ATTR_NOT_DELETED {
            get {
                return ResourceManager.GetString("ERR_REFM_ATTR_NOT_DELETED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REfM Error - Entity Attribute with key {0} and value {1} not updated.
        /// </summary>
        internal static string ERR_REFM_ATTR_NOT_UPDATED {
            get {
                return ResourceManager.GetString("ERR_REFM_ATTR_NOT_UPDATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RefM Error - Domain {0} not created.
        /// </summary>
        internal static string ERR_REFM_DOMAIN_NOT_CREATED {
            get {
                return ResourceManager.GetString("ERR_REFM_DOMAIN_NOT_CREATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RefM Error - Domain with id {0} not deleted.
        /// </summary>
        internal static string ERR_REFM_DOMAIN_NOT_DELETED {
            get {
                return ResourceManager.GetString("ERR_REFM_DOMAIN_NOT_DELETED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RefM Error - Domain {0} not updated.
        /// </summary>
        internal static string ERR_REFM_DOMAIN_NOT_UPDATED {
            get {
                return ResourceManager.GetString("ERR_REFM_DOMAIN_NOT_UPDATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RefM Error - Entity {0} not created.
        /// </summary>
        internal static string ERR_REFM_ENTITY_NOT_CREATED {
            get {
                return ResourceManager.GetString("ERR_REFM_ENTITY_NOT_CREATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RefM Error - Entity with id {0} not deleted.
        /// </summary>
        internal static string ERR_REFM_ENTITY_NOT_DELETED {
            get {
                return ResourceManager.GetString("ERR_REFM_ENTITY_NOT_DELETED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RefM Error - Entity {0} not updated.
        /// </summary>
        internal static string ERR_REFM_ENTITY_NOT_UPDATED {
            get {
                return ResourceManager.GetString("ERR_REFM_ENTITY_NOT_UPDATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RefM Error - API Url is missing..
        /// </summary>
        internal static string ERR_REFM_MISSING_APIURL {
            get {
                return ResourceManager.GetString("ERR_REFM_MISSING_APIURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RefM Error - Failed to retrieve Domain List.
        /// </summary>
        internal static string ERR_REFM_NO_RESULTS {
            get {
                return ResourceManager.GetString("ERR_REFM_NO_RESULTS", resourceCulture);
            }
        }
    }
}
